name: Install Inno Setup on Windows 2025

on: [push, pull_request]

jobs:
  install-inno-setup:
    runs-on: windows-2025

    steps:
      - name: Start timer
        id: start
        run: echo "start_time=$(Get-Date -Format o)" >> $env:GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Inno Setup Installer
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/ispack.exe" -OutFile "$env:TEMP\ispack.exe"

      - name: Install Inno Setup Silently
        run: |
          Start-Process -FilePath "$env:TEMP\ispack.exe" -ArgumentList "/VERYSILENT", "/NORESTART", "/SP-" -Wait

      - name: Verify ISCC.exe exists and get file size
        run: |
          $exePath = "C:\Program Files (x86)\Inno Setup 6\ISCC.exe"
          if (Test-Path $exePath) {
            $size = (Get-Item $exePath).Length / 1MB
            Write-Output "✅ Inno Setup installed successfully."
            Write-Output "📦 ISCC.exe size: $([math]::Round($size, 2)) MB"
          } else {
            Write-Error "❌ ISCC.exe not found at expected path."
            exit 1
          }

      - name: End timer and log duration
        run: |
          $start = [datetime]::Parse($env:start_time)
          $end = Get-Date
          $duration = $end - $start
          Write-Output "🕒 Total runtime: $($duration.ToString())"
