name: Show Actual Windows Image

on:
  workflow_dispatch:

jobs:
  check-image:
    runs-on: windows-latest

    steps:
      - name: Print runner image info
        shell: pwsh
        run: |
          Write-Output "Agent OS       : $env:AGENT_OS"
          Write-Output "Image OS Label : $env:ImageOS"
          Write-Output "Image Version  : $env:ImageVersion"
