name: Test GCC 4.8 Install on Ubuntu 24.04

on: [push , pull_request]

jobs:
  test-gcc-4-8-install:
    name: Install and Verify GCC 4.8
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update APT and download .deb files
        run: |
          sudo apt-get update

          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/g++-4.8_4.8.5-4ubuntu8_amd64.deb
          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libstdc++-4.8-dev_4.8.5-4ubuntu8_amd64.deb
          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8-base_4.8.5-4ubuntu8_amd64.deb
          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/gcc-4.8_4.8.5-4ubuntu8_amd64.deb
          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libgcc-4.8-dev_4.8.5-4ubuntu8_amd64.deb
          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/cpp-4.8_4.8.5-4ubuntu8_amd64.deb
          wget http://mirrors.kernel.org/ubuntu/pool/universe/g/gcc-4.8/libasan0_4.8.5-4ubuntu8_amd64.deb

      - name: Install downloaded packages
        run: |
          sudo apt-get install -y ./gcc-4.8_4.8.5-4ubuntu8_amd64.deb \
                                  ./gcc-4.8-base_4.8.5-4ubuntu8_amd64.deb \
                                  ./libstdc++-4.8-dev_4.8.5-4ubuntu8_amd64.deb \
                                  ./cpp-4.8_4.8.5-4ubuntu8_amd64.deb \
                                  ./libgcc-4.8-dev_4.8.5-4ubuntu8_amd64.deb \
                                  ./libasan0_4.8.5-4ubuntu8_amd64.deb \
                                  ./g++-4.8_4.8.5-4ubuntu8_amd64.deb || true

          sudo apt-get install -f -y

      - name: Verify GCC 4.8 installation
        run: |
          gcc-4.8 --version
          g++-4.8 --version
