name: Check Kotlin CLI Commands

on: [push, pull_request]

jobs:
  test-kotlin-cli:
    runs-on: windows-2025

    steps:
      - name: Download Kotlin Compiler (Latest)
        shell: pwsh
        run: |
          $url = "https://github.com/JetBrains/kotlin/releases/latest/download/kotlin-compiler.zip"
          Invoke-WebRequest -Uri $url -OutFile kotlin-compiler.zip
          Expand-Archive kotlin-compiler.zip -DestinationPath "$env:RUNNER_TEMP\kotlin"
          $kotlinBin = "$env:RUNNER_TEMP\kotlin\kotlinc\bin"
          echo "##[add-path]$kotlinBin"

      - name: Show Kotlin Tools in PATH
        shell: pwsh
        run: |
          Get-Command kotlin, kapt, kotlinc, kotlinc-jvm, kotlinc-js -ErrorAction SilentlyContinue | Format-Table

      - name: Run Kotlin CLI Tests
        shell: pwsh
        run: |
          Describe "Kotlin CLI Checks" {
              It "kapt" {
                  "kapt -version" | Should -ReturnZeroExitCode
              }

              It "kotlin" {
                  "kotlin -version" | Should -ReturnZeroExitCode
              }

              It "kotlinc" {
                  "kotlinc -version" | Should -ReturnZeroExitCode
              }

              It "kotlinc-jvm" {
                  "kotlinc-jvm -version" | Should -ReturnZeroExitCode
              }

              It "kotlinc-js" {
                  "kotlinc-js -version" | Should -ReturnZeroExitCode
              }
          }
              It "kotlinc" {
                  "kotlinc -version" | Should -ReturnZeroExitCode
              }

              It "kotlinc-jvm" {
                  "kotlinc-jvm -version" | Should -ReturnZeroExitCode
              }

              It "kotlinc-js" {
                  "kotlinc-js -version" | Should -ReturnZeroExitCode
              }
          }
        env:
          PATH: ${{ env.PATH }} # include kotlin in path
