name: Kotlin CLI Checks on Windows

on: [push, pull_request]

jobs:
  test-kotlin-cli:
    runs-on: windows-latest

    steps:
      - name: Get Latest Kotlin Version Tag
        id: get_kotlin_version
        shell: bash
        run: |
          latest=$(curl -s https://api.github.com/repos/JetBrains/kotlin/releases/latest | jq -r .tag_name)
          echo "Latest Kotlin version: $latest"
          echo "version=$latest" >> $GITHUB_OUTPUT

      - name: Download Kotlin Compiler ZIP
        shell: pwsh
        run: |
          $version = '${{ steps.get_kotlin_version.outputs.version }}'
          $version = $version.TrimStart("v")
          $url = "https://github.com/JetBrains/kotlin/releases/download/v$version/kotlin-compiler-$version.zip"
          Write-Host "Downloading from $url"
          Invoke-WebRequest -Uri $url -OutFile kotlin-compiler.zip

      - name: Extract Kotlin Compiler
        shell: pwsh
        run: |
          Expand-Archive kotlin-compiler.zip -DestinationPath "$env:RUNNER_TEMP\kotlin"
          $kotlinBin = "$env:RUNNER_TEMP\kotlin\kotlinc\bin"
          # Manually prepend the path so it works in the same step
          $env:PATH = "$kotlinBin;$env:PATH"

          Write-Host "PATH set to include Kotlin bin: $kotlinBin"

          # Show tools
          Write-Host "Checking available Kotlin CLI tools:"
          Get-Command kotlin, kapt, kotlinc, kotlinc-jvm, kotlinc-js -ErrorAction SilentlyContinue | Format-Table

          # Run CLI Tests
          $ErrorActionPreference = "Stop"

          function Test-CliTool {
              param (
                  [string]$cmd
              )
              Write-Host "`n🔹 Running: $cmd"
              $output = & $cmd 2>&1
              $exitCode = $LASTEXITCODE
              Write-Host "Exit Code: $exitCode"
              Write-Host "Output:`n$output"

              if ($exitCode -ne 0) {
                  Write-Error "`n❌ $cmd failed with exit code $exitCode"
                  exit 1
              } else {
                  Write-Host "`n✅ $cmd passed"
              }
          }

          Test-CliTool "kapt -version"
          Test-CliTool "kotlin -version"
          Test-CliTool "kotlinc -version"
          Test-CliTool "kotlinc-jvm -version"
          Test-CliTool "kotlinc-js -version"
